repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: https://github.com/pre-commit/pre-commit.git
    rev: v0.16.3
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
