language: python
dist: trusty
sudo: required
services:
    - docker
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py27 LATEST_GIT=1
        -   env: TOXENV=py35
            python: 3.5
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=pypy
            python: pypy-5.7.1
install: pip install coveralls tox
script: tox
before_install:
    # work around https://github.com/travis-ci/travis-ci/issues/8363
    - which python3.5 || (pyenv install 3.5.4 && pyenv global system 3.5.4)
    - git --version
    - |
        if [ "$LATEST_GIT" = "1" ]; then
            ./latest-git.sh
            export PATH="/tmp/git/bin:$PATH"
        fi
    - git --version
    - './get-swift.sh && export PATH="/tmp/swift/usr/bin:$PATH"'
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
